# Generated by Django 6.0.3 on 2026-05-11 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimation_accuracy', models.FloatField(default=1.0, help_text='Ratio: actual_hours / estimated_hours avg')),
                ('procrastination_score', models.FloatField(default=0.5)),
                ('tasks_completed', models.IntegerField(default=0)),
                ('subject_multipliers', models.JSONField(default=dict, help_text='Per-subject time multipliers learned from history')),
                ('avg_difficulty_given', models.FloatField(default=3.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('actual_hours', models.FloatField(help_text='How many hours did this actually take?')),
                ('difficulty_rating', models.IntegerField(help_text='1=Very Easy, 2=Easy, 3=Medium, 4=Hard, 5=Very Hard')),
                ('completed_on_time', models.BooleanField(default=True, help_text='Was it submitted before the deadline?')),
                ('notes', models.TextField(blank=True, help_text='Optional: what was hardest about this task?')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='api.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
                'unique_together': {('task', 'user')},
            },
        ),
    ]
