# Generated by Django 6.0.3 on 2026-05-27 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile_taskcompletion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessorAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('auto', 'Auto Generated'), ('manual', 'Student Raised')], default='auto', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='pending', max_length=15)),
                ('stress_score', models.FloatField(help_text='Dept stress score that triggered alert')),
                ('students_count', models.IntegerField(default=0, help_text='Number of students affected')),
                ('message', models.TextField(blank=True, help_text='Auto-generated or student message')),
                ('suggestion', models.TextField(blank=True, help_text='AI suggested action e.g. extend deadline')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affected_tasks', models.ManyToManyField(blank=True, related_name='alerts', to='api.task')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='api.department')),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
