# Generated by Django 6.0.3 on 2026-05-27 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_professoralert'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='department_files/%Y/%m/')),
                ('file_type', models.CharField(choices=[('assignment', 'Assignment'), ('lab', 'Lab Copy'), ('notes', 'Notes'), ('other', 'Other')], default='other', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.IntegerField(default=0, help_text='File size in bytes')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.department')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
