# Generated by Django 6.0.3 on 2026-05-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_departmentfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='professoralert',
            name='resolve_token',
            field=models.CharField(blank=True, help_text='Unique token for professor to resolve via email link', max_length=64),
        ),
        migrations.AddField(
            model_name='professoralert',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professoralert',
            name='resolved_by_professor',
            field=models.BooleanField(default=False, help_text='True when professor clicks resolve in email'),
        ),
    ]
